import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div>
            <div>
              <div className="border-b">
                <div className="max-w-[1200px] hidden md:flex md:justify-between items-center py-3 m-auto">
                  <Link href="/">
                    <Image src="/logo.png" width={60} height={60} alt="Logo" />
                  </Link>
                  <Link
                    href="/"
                    className="no-underline bg-primary-1 px-5 py-4 rounded-[50px] text-white font-semibold"
                  >
                    Install Google Sheet Add-On
                  </Link>
                </div>
              </div>
            </div>
          </div>

          {children}
        </Providers>
      </body>
    </html>
  );
}
